### ISSUE TITLE
Add GCC9, Clang8+9 CI builds

### ISSUE THREAD

**Issue by dermojo** [dermojo/ooopsi#10]

**Comment by dermojo** [comment]
GCC 9 + Clang 8 merged with PR12, but Clang 9 isn't yet available on Travis

**Comment by d-frey** [comment]
If you are interested in using clang-9 and even clang-10, you need to "manually" add the repository. Have a look here: https://github.com/taocpp/PEGTL/blob/master/.travis.yml

**Comment by dermojo** [comment]
@d-frey Thanks, I was waiting for the package to become available!

**Comment by d-frey** [comment]
GCC 9+10 are available now (in the usual whitelisted ubuntu-toolchain-r-test repo), but I seem to remember that Travis is not eager to enable the llvm 9+10 repos (each having a specific name) as the above manual option is available. So I wouldn't hold by breath for LLVM whitelisting, just adding the repos manually gives you the same packages anyways.

**Comment by dermojo** [comment]
I copied the approach from your travis config, works like a charm :)
